Increment3
HappyKod/ServiceShortLinks pull request #2
Opened 2022-08-29 18:30 UTC by HappyKod

2022-08-31 11:33 UTC, tmvrus requested changes

2022-08-31 11:33 UTC, tmvrus commented on internal/app/handlers/handlers.go
> +	r.POST("/", func(context *gin.Context) { PutHandler(context) })
Оборачивать хендлеры в данном случае бессмысленно, GivHandler и PutHandler можно передавать как есть

2022-08-31 11:33 UTC, tmvrus commented on go.mod
> +module ServiceShortLinks
Это, безусловно, валидное имя для go-модуля, но в индустрии принято несколько иначе именовать,
предлагаю ServiceShortLinks -> github.com/HappyKod/ServiceShortLinks

2022-08-31 11:33 UTC, tmvrus commented on cmd/shortener/main.go
> +		log.Fatalln(errors.New("Ошибка иницилизации mem_storage " + err.Error()))
нет большого смысла вызывать errors.New что бы сгенерировать ошибку которая все равно превратится в строку, можно сразу передать в Fataln строку - "Ошибка иницилизации mem_storage " + err.Error()

2022-08-31 11:33 UTC, tmvrus commented on internal/app/handlers/PutHandler.go
> +	defer c.Request.Body.Close()
этот вызов может вернуть ошибку, ее следует логировать

2022-08-31 11:33 UTC, tmvrus commented on internal/app/handlers/PutHandler.go
> +			http.Error(c.Writer, "Ошибка получение данных из хранилища ", http.StatusInternalServerError)
после того как тут вы отправите ошибку клиенту, хендлер продолжит работать, поскольку не завершен

2022-08-31 11:33 UTC, tmvrus commented on internal/app/handlers/PutHandler.go
> +	_, err = c.Writer.WriteString("http://" + path.Join(constans.Address, key))
эту ошибку достаточно просто логировать, поскольку она как раз означает что мы не смогли отправить что-то клиенту, пытаться отправить данные второй раз при помощи http.Error в нашем случае бесмысленно

2022-08-31 11:33 UTC, tmvrus commented on internal/app/handlers/handlers_test.go
> +var Key string
неясно зачем тут глобальная переменная

2022-08-31 11:33 UTC, tmvrus commented on internal/app/handlers/handlers_test.go
> +				responseCode:     307,
для такие кодов лучше использовать константы пакета http.StatusXXX это повысит читаемость кода

2022-08-31 11:33 UTC, tmvrus commented on internal/app/server/server.go
> +}
весь этот код можно упростить до return server.ListenAndServe()
и сразу появится вопрос - нужна ли для этого отдельная ф-ия

2022-08-31 11:33 UTC, tmvrus commented on internal/storage/strorage.go
> +//Набор методов для работы с хранилищем
не хватает пробела между // и комментарием, дело в том, что если пробела нет, то компилятор считает что эти комментарии предназначены для него а не для человека

2022-08-31 11:33 UTC, tmvrus commented on utils/utils.go
> +package utils
utils очен неудачное имя для пакета, поскольку "means nothing", рекомендую создать отдельный пакет validator и generator

2022-08-31 11:33 UTC, tmvrus commented on internal/storage/memstorage/mem-storage.go
> +type MemStorage struct {
не ясно почему MemStorage содержит прослойку connect а не сразу 
```
mu    sync.Mutex
cache map[string]string
```
ведь connect не содержит никакой отдельной логики

2022-08-31 11:33 UTC, tmvrus commented on internal/storage/memstorage/mem-storage.go
> +func Init() (*connect, error) {
в индустрии принято использовать New/new вместо Init в конструкторах.
init - зарезервированная ф-я для инициализации модуля и нужна в специфических случаях
https://golangdocs.com/init-function-in-golang

2022-08-31 11:33 UTC, tmvrus commented on internal/app/server/config.go
> +func Config(r *gin.Engine) *http.Server {
неясно почему ф-я Config создает Server
возможно лучше NewServer(config)

2022-08-31 11:33 UTC, tmvrus commented on internal/constans/constants.go
> +var Address = "localhost:8080"
Такое лучше делать константой

2022-08-31 11:33 UTC, tmvrus commented on internal/constans/constants.go
> +var GlobalStorage storage.Storages
вот это не очень удачное решение, это не безопасно с точки зрения доступа, + усложняет тестирование, посколько вся работа должна выполнятся только с 1 экземпляром storage
рекомендую ознакомиться с концепцией  [dependency injection](https://www.google.com/search?q=dependency+injection+golang&oq=dependency+injection+golang&aqs=chrome..69i57j0i512l2j0i22i30j0i15i22i30j0i22i30l5.5202j1j4&sourceid=chrome&ie=UTF-8)

2022-08-31 11:33 UTC, tmvrus commented on internal/app/handlers/handlers_test.go
> +		log.Fatalln(errors.New("Ошибка иницилизации mem_storage " + err.Error()))
для этого есть служебный вызов t.Fatal он позволяет корректно завершить тесты

2022-08-31 11:33 UTC, tmvrus commented on internal/app/handlers/handlers_test.go
> +	fmt.Println(Key)
это видимо остаток какой-то отладки

2022-08-31 17:14 UTC, HappyKod commented on internal/storage/memstorage/mem-storage.go
> +type MemStorage struct {
Я предполагал дальнейшее развитие этой структуры

2022-09-01 12:17 UTC, tmvrus approved these changes
Di-контейнер с первого спринта это оч сильно, это не совсем то, что я имел ввиду, но получилось даже лучше.

2022-11-15 18:48 UTC, merged